"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class observ_t(object):
    __slots__ = ["q", "qdot", "orientation", "pre_action", "cmd_vel"]

    __typenames__ = ["double", "double", "double", "double", "double"]

    __dimensions__ = [[12], [12], [6], [12], [6]]

    def __init__(self):
        self.q = [ 0.0 for dim0 in range(12) ]
        self.qdot = [ 0.0 for dim0 in range(12) ]
        self.orientation = [ 0.0 for dim0 in range(6) ]
        self.pre_action = [ 0.0 for dim0 in range(12) ]
        self.cmd_vel = [ 0.0 for dim0 in range(6) ]

    def encode(self):
        buf = BytesIO()
        buf.write(observ_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>12d', *self.q[:12]))
        buf.write(struct.pack('>12d', *self.qdot[:12]))
        buf.write(struct.pack('>6d', *self.orientation[:6]))
        buf.write(struct.pack('>12d', *self.pre_action[:12]))
        buf.write(struct.pack('>6d', *self.cmd_vel[:6]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != observ_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return observ_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = observ_t()
        self.q = struct.unpack('>12d', buf.read(96))
        self.qdot = struct.unpack('>12d', buf.read(96))
        self.orientation = struct.unpack('>6d', buf.read(48))
        self.pre_action = struct.unpack('>12d', buf.read(96))
        self.cmd_vel = struct.unpack('>6d', buf.read(48))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if observ_t in parents: return 0
        tmphash = (0x868a4ee86bb5fd9b) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if observ_t._packed_fingerprint is None:
            observ_t._packed_fingerprint = struct.pack(">Q", observ_t._get_hash_recursive([]))
        return observ_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", observ_t._get_packed_fingerprint())[0]

