"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class action_t(object):
    __slots__ = ["tau"]

    __typenames__ = ["double"]

    __dimensions__ = [[12]]

    def __init__(self):
        self.tau = [ 0.0 for dim0 in range(12) ]

    def encode(self):
        buf = BytesIO()
        buf.write(action_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>12d', *self.tau[:12]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != action_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return action_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = action_t()
        self.tau = struct.unpack('>12d', buf.read(96))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if action_t in parents: return 0
        tmphash = (0x695527eb5563f8fc) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if action_t._packed_fingerprint is None:
            action_t._packed_fingerprint = struct.pack(">Q", action_t._get_hash_recursive([]))
        return action_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

